<header class="dashboard_header">
    <div class="dashboard_header_title">
        <h1 class="icon-blog">Posts</h1>
        <p class="dashboard_header_breadcrumbs">
            &raquo; <?= ADMIN_NAME; ?>
            <span class="crumb">/</span>
            <a title="<?= ADMIN_NAME; ?>" href="dashboard.php?wc=home">Dashboard</a>
            <span class="crumb">/</span>
            <a title="Todos os Posts" href="dashboard.php?wc=posts/home">Posts</a>

        </p>
    </div>
    <div class="dashboard_header_search" style="width: 60%">
        <form style="width: 100%; display: inline-block;" name="searchCategoriesPost" action="" method="post"
              enctype="multipart/form-data" class="ajax_off">
            <?= $DateFilters; ?>
            <?= $QuickSearch; ?>
            <?= $valueStatus; ?>
            <?= $ValuesOfItemPerPage; ?>
        </form>
    </div>
</header>

<div class="dashboard_content">
    <div class="zf-table-wrap  form-inline">
        <div class="box box100">
            <div class="box-header">
                <?php if ($name): ?>
                    <h3 class="box-title">
                        <?= $name ?>
                    </h3>
                <?php endif; ?>

                <div class="box-tools">

                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <?= $table ?>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="dataTables_paginate paging_bootstrap pagination pull-left">
                    <ul class="paginator">
                        <?= $paginator; ?>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <?php echo $paramsWrap; ?>
</div>
