<script src="<?=BASE?>/_app/Library/Table/www/templates/js/moment.min.js"></script>
<script src="<?=BASE?>/_app/Library/Table/www/templates/js/locale/pt-br.js"></script>
<script src="<?=BASE?>/_app/Library/Table/www/templates/js/daterangepicker.js"></script>
<!--<script src="--><?//=BASE?><!--/_app/Library/Table/www/templates/plugins/iCheck/icheck.min.js"></script>-->
<script src="<?=BASE?>/_app/Library/Table/www/templates/js/call-table.js"></script>